name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install missing dependencies
        run: npm install react-hook-form @hookform/resolvers zod \
         @radix-ui/react-aspect-ratio @radix-ui/react-avatar \
         @radix-ui/react-context-menu @radix-ui/react-dropdown-menu \
         @radix-ui/react-hover-card @radix-ui/react-menubar \
         @radix-ui/react-navigation-menu @radix-ui/react-popover \
         @radix-ui/react-progress @radix-ui/react-radio-group \
         @radix-ui/react-scroll-area @radix-ui/react-select \
         @radix-ui/react-separator @radix-ui/react-slider \
         @radix-ui/react-switch @radix-ui/react-tabs \
         @radix-ui/react-toggle-group @radix-ui/react-toggle \
         @radix-ui/react-tooltip embla-carousel-react recharts \
         react-day-picker drizzle-orm drizzle-zod input-otp vaul


      - name: Build
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './client/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
